name: Lint and Format

on: [push]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: lint & format
        run: |
          pnpm lint
          pnpm format
          git status && git diff --exit-code

      - name: Next.js build
        run: |
          pnpm build

      - name: Use reviewdog eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
